using System.Xml;
using System;
using Google_Sync.src.Outlook;

namespace Google_Sync.src
{
    class XML
    {
        private XmlTextWriter xmlWriter;
        
        public XML()
        {
            xmlWriter = new XmlTextWriter(System.Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + @"\Google Sync\Outlook.xml", System.Text.Encoding.UTF8);
            xmlWriter.Formatting = Formatting.Indented;
        }

        public void write(Item[] itemArray)
        {
            xmlWriter.WriteStartDocument();
            xmlWriter.WriteComment("Build by Google Outlook sync - do not edit this file");
            xmlWriter.WriteStartElement("Appointments");
            foreach (Item item in itemArray)
            {
                xmlWriter.WriteStartElement("Appointment");
                xmlWriter.WriteElementString("ID", item.id);
                xmlWriter.WriteElementString("Subject", item.subject);
                xmlWriter.WriteElementString("Location", item.location);
                xmlWriter.WriteElementString("StartTime", item.startTime);
                xmlWriter.WriteElementString("EndTime", item.endTime);
                xmlWriter.WriteElementString("Recipients", item.group);
                xmlWriter.WriteElementString("Location", item.location);
                xmlWriter.WriteStartElement("Recurring", item.isReturning.ToString());
                xmlWriter.WriteEndElement();
                xmlWriter.WriteEndElement();
                
            }
            xmlWriter.WriteEndElement();
            xmlWriter.WriteEndDocument();
            xmlWriter.Flush();
            xmlWriter.Close();
        }
    }
}

